### PR TITLE
Enable HTTP proxy support from environment

### PR DESCRIPTION
**Pull request by vr**

### CODE REVIEW

**Comment by alieander** [comment]
I somehow expected that call `start` on an existing `Http` object would act in some way like calling the class method `start`... They are however very different beasts...

Sadly the class method looks like it needs this sort of thing to get back to the defaults of calling `new`.

👍 looks good to me

Side note: I don't see anywhere that this `http` object is `finish`ed...

**Comment by thommahoney** [comment]
There is some concern internally that this change makes this library vulnerable to https://httpoxy.org/

**Comment by vr** [comment]
no it don't make the library vulnerable as stated in : 
  - https://httpoxy.org/#why
  - http://ruby-doc.org/stdlib-2.3.1/libdoc/uri/rdoc/URI/Generic.html#method-i-find_proxy
  - https://bugs.ruby-lang.org/issues/6546

**Comment by vr** [comment]
so ? any update on this ?

**Comment by drbrain** [comment]
My name is Eric Hodel and I approve this pull request.

**Pull request merged**
