### PR TITLE
Add `format_version` to S3Logging and Syslog resources

### PR DESCRIPTION
**Pull request by schisamo**
Signed-off-by: Seth Chisamore <schisamo@chef.io>

### CODE REVIEW

**Comment by schisamo** [comment]
The Travis failure is on Ruby 1.9.3 only and appears to be related to a RuboCop incompatibility with Ruby 1.9.3.

**Comment by lanej** [comment]
See https://docs.fastly.com/api/logging#logging_s3

**Comment by lanej** [comment]
Thanks @schisamo

**Comment by cwebberOps** [comment]
@lanej is it possible to get a gem released with this code?

**Comment by lanej** [comment]
@cwebberOps https://rubygems.org/gems/fastly/versions/1.6.1

**Pull request merged**
