### PR TITLE
Add ACL and ACL Entry Support

### PR DESCRIPTION
**Pull request by wrightp**
ACL and ACLEntry API support
- `singularize` class method
- tests for ACL and managing entries from the ACL instances
- tests for ACL entries (fully instantiated)
- linted the new files

@schisamo @lanej

### CODE REVIEW

**Comment by schisamo** [comment]
This should be ready for final review @lanej.

**Comment by lanej** [comment]
@schisamo LGTM.

**Comment by schisamo** [comment]
@lanej Can we get this merged and 🚢  a new `fastly` gem to Rubygems.org?

**Comment by lanej** [comment]
@schisamo https://rubygems.org/gems/fastly/versions/1.7.0

**Comment by schisamo** [comment]
@lanej :heart:

**Pull request merged**
