### PR TITLE
rubocop

### PR DESCRIPTION
**Pull request by jamesarosen**
* add `bundle exec rubocop` to `.travis.yml` build
 * fix or ignore all rubocop errors and warnings

### CODE REVIEW

**Comment by jamesarosen** [comment]
I don't know what to do about the warnings in Ruby 1.9. They don't show up in any of the other versions.

**Comment by drbrain** [comment]
I think we should use [ruby-style's .rubocop.yml](https://github.com/fastly/ruby-style/blob/master/.rubocop.yml)

**Comment by jamesarosen** [comment]
> I think we should use ruby-style's .rubocop.yml

That's a private gem. Do you want to publish it to rubygems.org?

**Comment by drbrain** [comment]
No, copy-paste would be fine for now

**Comment by drbrain** [comment]
Oh, this PR has been open for a long time, what should we do?

PS: Thanks [github open PR review request list](https://github.com/pulls/review-requested)

**Pull request closed without merging**
