### PR TITLE
v4

### PR DESCRIPTION
**Pull request by Integralist**

### CODE REVIEW

**Review by harmony7 — APPROVED** [review]
I'm good with this.

If there are any additional automated builds, please feel free to add them to the end of this branch before merging.

**Comment by gagalago** [comment]
I don't see any changelog for this version. what should we pay attention for to when upgrading?

**Comment by Integralist** [comment]
Hi @gagalago 

Apologies for the confusion. 

I intended to publish a change log but a last minute priority prevented me. I'll be sure to get one written up ASAP, and I'll ping back to this thread once it's done.

Thanks.

**Comment by Integralist** [comment]
Hi @gagalago 

Thanks for your patience. I was on PTO shortly after I last commented and so didn't get round to updating the change log.

I've added a new entry to the [CHANGELOG.md](https://github.com/fastly/fastly-ruby/blob/main/CHANGELOG.md) with links to what is hopefully useful information regarding the new v4 release.

**Pull request merged**
